---
- name: IOS Firmware Upgrade
  hosts: Switch
  connection: network_cli
  gather_facts: no

  vars:
    compliant_ios_version: 15.2(7)E0a
    src_image: c2960x-universalk9-mz.152-7.E0a.bin
    src_image_size_kb: 26000
    image_source_server: 192.168.1.27
    src_image_md5: 56754cd55e42d84acea5dfd1628d99b9
    ansible_command_timeout: 1500

  tasks:
   - name: Gather Switch Information.
     ios_facts:
   
   - name: Display Switch Information.     
     debug:
       msg: 
         - "hostname {{ ansible_net_hostname }}"
         - "Model {{ ansible_net_model }}"
         - "Serial {{ ansible_net_serialnum }}"
         - "OS version {{ ansible_net_version }}"
         - "Running Image {{ansible_net_image }}"
         - "Filesystem  {{ ansible_net_filesystems_info['flash:'].spacefree_kb | int }}"
         - "Configured IP address {{ansible_net_all_ipv4_addresses }}"
         - "CDP Neighbours {{ ansible_net_neighbors }}"
   
   - name: UPGRADE NON COMPLIANT SWITCH 
     block:
     - name: SETTING CONSOLE LINE TO LOCAL AUTHENTICATION
       ios_config:
          commands:
             - line console 0
             - exec-timeout 50

     - name: COPY IMAGE TO SWITCH
       ios_command:
          commands:
             - command: 'copy http://{{image_source_server}}/{{src_image}} flash:/{{src_image}}'
               prompt: '[confirm]'
               answer: "\r"
 
     - name: GATHER MD5 OF COPIED IMAGE.
       ios_command:
          commands:
             - command: 'verify /md5 flash:/{{src_image}}'
       register: md5_result

     - name: SETTING BOOT PATH IF MD5 IS MATCHED.
       ios_config:
          commands:
             - no boot system
             - boot system flash:/{{src_image}}
          save_when: always

       when: 'src_image_md5 in md5_result.stdout[0]'


     when: (ansible_net_version != compliant_ios_version and ansible_net_filesystems_info['flash:'].spacefree_kb|int > src_image_size_kb|int)
